### ISSUE TITLE
Boolean values without quotation marks cannot be parsed

### ISSUE THREAD

**Issue by ahmedyarub** [yaml/libyaml#223]
Is it a requirement to have quotation marks around boolean values? Or is this a bug?

**Comment by perlpunk** [comment]
More information please

**Comment by ahmedyarub** [comment]
https://github.com/kubernetes-client/c uses libyaml to parse the configuration file of Kubernetes. The configuration looks like this:
```
apiVersion: v1
clusters:
  - cluster:
        insecure-skip-tls-verify: true
        server: https://1111111111111111.gr7.us-west-2.eks.amazonaws.com
    name: arn:aws:eks:us-west-2:11111111:cluster/eks-dev

```
That insecure-skip-tls-verify property can be parsed without any problem by Kubernetes own tools like kubectl. They do not use libyaml. But the C client mentioned above which uses libyaml crashes unless there are quotation marks for the boolean value, which means that it should be "true" instead of true.
