### ISSUE TITLE
YAML_FLOW_MAPPING_START_TOKEN

### ISSUE THREAD

**Issue by bkaraujo** [yaml/libyaml#307]
Hello,

I'm parsing a yaml and inside a array there is a flow mapping. I was expecting `YAML_BLOCK_SEQUENCE_START_TOKEN` to be issued before the `YAML_FLOW_MAPPING_START_TOKEN` but it does not go that way.

The following yaml produces the YAML_BLOCK_SEQUENCE_START_TOKEN after properties:

```
      camera:
        properties:
          - name: "depth"
            value: "-1.0, 1.0"
          - name: "rectangle"
            value: "-21.0, 21.0, -21.0, 21.0"
```

The following yaml does not produces the YAML_BLOCK_SEQUENCE_START_TOKEN after properties:

```
      camera:
        properties:
          - { name: "depth", value: "-1.0, 1.0" }
          - { name: "rectangle", value: "-21.0, 21.0, -21.0, 21.0" }
```
